---
- hosts: localhost
  vars:
    - server_hostname: docker.private.repo
    - key_size: 4096
    - passphrase: # Set if you want passphrase
    - key_type: RSA # Others include DSA, ECC, Ed25519, Ed448, X25519, X448
    - country_name: IN
    - email_address: admin@computingforgeeks.com
    - organization_name: automaton

  tasks:
    - name: Generate an OpenSSL private key
      openssl_privatekey:
        path: "./certificates/domain.key"
        size: "{{ key_size }}"
        type: "{{ key_type }}"
        backup: yes
    
    - name: Generate an OpenSSL Certificate Signing Request with Subject information
      openssl_csr:
        path: "./certificates/domain.csr"
        privatekey_path: "./certificates/domain.key"
        country_name: "{{ country_name }}"
        organization_name: "{{ organization_name }}"
        email_address: "{{ email_address }}"
        common_name: "{{ server_hostname }}"

    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: "./certificates/domain.crt"
        privatekey_path: "./certificates/domain.key"
        csr_path: "./certificates/domain.csr"
        provider: selfsigned